## 1. Schleifen

### 1.1 for-Schleife (Zählerschleife)

In [ ]:
#range(Startwert, Endwert, Schrittweite)

for i in range(0,10,1):
    print("Schleifen-Durchlauf", i)

###  1.2 Schleife mit Liste

In [ ]:
myList = ["eins", "zwei", "drei"]

for i in myList:
    print(i)

1.3 while-Schleife (Standard)

In [ ]:
count = 0

while count < 5:
    print(count)
    count = count +1

1.4 while-True-Schleife (Fußgesteuert)

In [ ]:
while True:
    user_input = input("Geben Sie 'q' ein, um die Schleife zu beenden: ")
    if user_input == 'q':
        break  # Beendet die Schleife, wenn 'q' eingegeben wird
    else:
        print(user_input, "Schleife läuft weiter...")

1.5 Erweiterte Schleifensteuerung

In [ ]:
for i in range(10):
    if i == 3:
        continue  # Überspringe die 3
    if i == 7:
        break  # Beende die Schleife vorzeitig
    print(i)

2. Listen

2.1 Listenfunktionen

In [ ]:
myList = ["eins", "zwei", "drei", "vier", "fünf","hallo"]

#an Liste anfügen
myList.append("sechs")

#an bestimmte Position einfügen
myList.insert(2,"2")

#aus Liste entfernen
myList.remove("drei") #Entfernt das erste Vorkommen eines Elements.
myList.pop(4) #Entfernt und gibt ein Element an einer bestimmten Position zurück.
del myList[0] #Löscht ein Element an einer bestimmten Position. (-1 für letzter Index in Liste)

#Listen Länge
len(myList)

#Zugriff auf Listenindex
element = myList[1]

#Liste umdrehen
myList.reverse()

#Liste nach abc sortieren
myList.sort()

#Jedes 2. Ausgeben
print(myList[::2])

#Listen kombinieren
neueListe = myList + [4,5,6]

#Liste an Liste anhängen
myList.extend(["mirabelle","pflaume"])

#Das größte Element einer Liste bestimmen
maxwert = max(myList)

#Das kleinste Element einer Liste bestimmen
minwert = min(myList)

#Prüfen ob ein Element in der Liste ist
if ("hallo" in myList):
    print ("Es steht Hallo in der Liste")

#Püfen ob ein Element nicht in einer Liste ist
if ("hallo" not in myList):
    print ("Da ist leider kein hallo")



print(myList)

3. Tupel

Tupel können nicht verändert werden.

Ein Tupel wird durch Zuweisung definiert. Der Datentyp ist tupel. Tupel werden mit runde Klammen
umschlossen.

Funktionen wie auf Index zugreifen oder Schleifen ist wie bei Listen

In [ ]:
tupel1 = (1,2,3,4,5)
tupel2 = ("apfel","birne","kirsche")

#Tupel mit nur einem Element
tupel3 = ("apfel",)

#Tupel in Liste umwandeln
tupelList = list(tupel1)

4. Python Dictionary

Ein Dictionary ist eine Sammlung von key-value (Schlüssel-Wert) Paaren. Die Keys sind normalerweise
Strings oder int-Zahlen. Die Values können wiederum alle Datentypen enthalten.

4.1 Dictionary allgemein

In [33]:
dict1 = {'name':'Meier','vorname':'Ilse'}
print (dict1['name'])


#Auf existierenden Key prüfen
if "name" in dict1:
    print (dict1['name'])

#Element hinzufügen
dict1['strasse'] = 'Bergsonstraße'
print(dict1)


Meier
Meier
{'name': 'Meier', 'vorname': 'Ilse', 'strasse': 'Bergsonstraße'}
Meier


4.2 Dictionary Funktionen

In [34]:
#Gibt die Anzahl der Dictionary-Einträge (Items) zurück.
len(d)

#äGibt den Wert des Eintrags mit dem übergebenen key zurück.
dict1[key]

#Setzt den Wert für den Schlüssel key auf value
dict1[key] = value

#Ergibt True wenn es den key gibt, sonst False.
key in dict1

#Ergibt False wenn es den key gibt, sonst True.
key not in dict1

#Löscht alle Elemente aus dem Dictionary.
dict1.clear()

#Erzeugt eine Kopie des Dictionarys.
dict1.copy()

#Gibt den Wert von key zurück, wenn key existiert ansonsten, default. Wenn default nicht angegeben ist, wird
#None zurück gegeben, so dass die Methode nie einen Fehler erzeugt.
dict1.get(key[,default])

#Erzeugt einen View auf alle Keys (List). Die Liste verändert sich mit einer Änderung im Dictionary
dict1.keys()

#Wenn key im dictionary vorhanden ist, wird das Element gelöscht und der key zurück gegeben. Ansonsten
#wird der Wert default zurück gegeben. Fenn default nicht definiert wird wird ein Fehler erzeugt.
dict1.pop(key[,default])

#Das Dictionary wird mit den key/value pairs von other ergänzt. Existierende keys werden überschrieben. Rückgabewert ist None.
dict1.update([other])

#Gibt einen view aller values zurück (Liste).
dict1.values()

#Liefert einen view über alle key,value Paare. Kann in einer Schleife verwendet werden. Die Liste verändert
#sich mit einer Änderung im Dictionary. Siehe Beispiel unten
dict1.items()




SyntaxError: invalid syntax (1599550909.py, line 24)

4.3 Schleifen mit Dictionaries

In [ ]:
#Eine Schleife über ein Dictionary liefert die Werte für die Keys im Dictionary: 
for key in dict1:
 print(f"Key = {key} Value= {dict1[key]} ")

#Über die Funktion items() können alle key,value – Paare in einer Tupel-Liste abgerufen werden. Darüber
#kann man dann wieder mit einer Schleife die Tupel abrufen.

print(dict1.items())
for key,value in dict1.items():
 print(f"Key = {key} Value= {value} ")


5. Numpy Arrays

In [2]:
import numpy as np

x = np.array([[1,2],
              [3,4],
              [5,6]])

#Infos über array
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

array_info(x)


ndim: 2
shape: (3, 2)
size: 6
dtype: int32
values:
[[1 2]
 [3 4]
 [5 6]]



In [3]:
#Array umdrehen

print(x[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [4]:
#nur 1. Zeile ausgeben
print(x[0, :])

[1 2]


In [ ]:
#nur 1. Spalte ausgeben
print(x[:, 0])

5.1 Numpy funktionen/berechnen

In [48]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])

#Matrix mit 0 gefüllt erstellen
np.full(shape=(5,5), fill_value=1)

#Matrix transponieren
np.transpose(a)

#Matrix mit gefüllten 0en erstellen
np.zeros(shape=(3,3))

#Matrix mit 1er füllen
np.ones((5,5))

#Einheitsmatrix erstellen
np.identity(3)

#Matrix diagonale füllen
np.diag()

#Matrix oberes dreieck (u steht für Upper)
np.triu_indices(3,1)

#Matrix unteres dreieck (l steht für Lower)
np.tril_indices(3,-1)

#Zufallszahl  [low Grenze ist dabei, heigh Grenze ist nicht dabei, Matrix größe]
print(np.random.randint(low=1, high=10, size=(5,5)))

#Zählt alle werte die nicht null sind
np.count_nonzero(a)

#Zählt alle werte kleiner 0
np.count_nonzero(a<0)

#Absolutwert (aus - wird +)
np.absolute(-1)

#Slice
N = np.zeros((5,5))

#letzer index (4) nicht dabei
N[::4,::1] = 1
N[::1,::4] = 1

#[1:-1,1:-1] = 1 #innen 1er

[[6 5 6 2 8]
 [9 1 1 8 6]
 [9 5 1 7 4]
 [7 3 3 7 9]
 [4 9 6 7 9]]


1

5.2 Matritzen multiplizieren

In [ ]:
out = np.matmul(np.transpose(b), np.transpose(a))

#oder 
out = np.transpose(b) @ np.transpose(a)

5.3 Matrix mit Skalar mutliplizieren

In [28]:
out = np.multiply(2, a)

#oder
out = 2 * a

print(out)

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


5.4 Determinante berechnen

In [23]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])

print(np.linalg.det(a))

-2.0000000000000004
